#!/usr/bin/env python3
"""
Bonus experiment: multilingual silos (one language per silo).

Four silos, each fixed to one language (English, Spanish, French, Estonian),
all training on the same two known fictional diseases (Velarex, Sornathis) in
equal proportion -- so disease label is IID across silos and language is the
only silo-identity axis. Opening statements are generated by phi3:mini via
MultilingualOllamaDataSource, prompted to respond in the silo's language
(no translated phrase banks; see that class's docstring for the follow-up-
turns-stay-English limitation). Backbone is distilbert-base-multilingual-cased
instead of the rest of the paper's distilbert-base-uncased, since the
English-only tokenizer would not handle Spanish/French/Estonian text
meaningfully.

This is NOT one of falsification.md's pre-registered controls -- it is a
separate, exploratory, single-seed check of a new heterogeneity axis
(linguistic non-IID) that the rest of the paper does not study. Two questions,
evaluated by unsupervised clustering against two different label sets on the
same embeddings:
  (1) Does disease-structured clustering (the paper's Claim 1) still emerge
      when each silo also has a distinct, fixed language?
  (2) Does the embedding space instead organize primarily by language/silo
      identity rather than by disease?
"""
from __future__ import annotations

import argparse
import json
import random
import types
from pathlib import Path

import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics import adjusted_rand_score, silhouette_score

OUT_DIR = Path("results/multilingual_silos")
OUT_DIR.mkdir(parents=True, exist_ok=True)

LANGUAGES = ["en", "es", "fr", "et"]
DISEASES = ["velarex", "sornathis"]
SEVERITIES = ["mild", "moderate", "severe"]


def _make_event(text: str, disease: str, language: str) -> dict:
    return {
        "text": text,
        "label": disease,
        "gt_disease": disease,
        "language": language,
    }


def _generate_events(language: str, n_per_disease: int, seed: int, client,
                     diseases: list[str] | None = None) -> list[dict]:
    """Generate n_per_disease events per disease in `diseases` (default DISEASES), in the given language."""
    from simulation.data_sources import MultilingualOllamaDataSource
    from simulation.symptom_language import Personality

    rng = random.Random(seed)
    source = MultilingualOllamaDataSource(language=language, client=client, seed=seed)
    personalities = list(Personality)

    events = []
    for disease in (diseases or DISEASES):
        for i in range(n_per_disease):
            severity_band = SEVERITIES[i % 3]
            severity_val = {"mild": 0.2, "moderate": 0.5, "severe": 0.85}[severity_band]
            inner_state = types.SimpleNamespace(severity=severity_val, disease_name=disease)
            personality = rng.choice(personalities)
            days = rng.randint(1, 10)
            text = source.opening_statement(inner_state, days, personality)
            events.append(_make_event(text, disease, language))
    return events


def _project_umap(cls_emb: np.ndarray, seed: int = 42) -> np.ndarray:
    import warnings
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        import umap
        return umap.UMAP(n_components=2, random_state=seed, n_jobs=1).fit_transform(cls_emb)


def _extract_cls(learner, texts: list[str]) -> np.ndarray:
    import torch
    enc = learner._tokenizer(
        texts, padding=True, truncation=True, max_length=128, return_tensors="pt"
    )
    model = learner.model
    dev = next(model.parameters()).device
    enc = {k: v.to(dev) for k, v in enc.items()}
    model.eval()
    with torch.no_grad():
        out = model(**enc, output_hidden_states=True)
    return out.hidden_states[-1][:, 0, :].cpu().numpy()


def _evaluate(learner, probe_texts, probe_disease, probe_language,
              probe_pools: dict | None = None) -> dict:
    embs = _extract_cls(learner, probe_texts)

    km_disease = KMeans(n_clusters=2, random_state=0, n_init=10).fit(embs)
    ari_disease = float(adjusted_rand_score(probe_disease, km_disease.labels_))
    sil_disease = float(silhouette_score(embs, probe_disease))

    km_lang = KMeans(n_clusters=len(LANGUAGES), random_state=0, n_init=10).fit(embs)
    ari_lang = float(adjusted_rand_score(probe_language, km_lang.labels_))
    sil_lang = float(silhouette_score(embs, probe_language))

    metrics = {
        "ari_vs_disease": ari_disease,
        "silhouette_vs_disease": sil_disease,
        "ari_vs_language": ari_lang,
        "silhouette_vs_language": sil_lang,
    }

    if probe_pools is not None:
        pooled_events = [ev for pool in probe_pools.values() for ev in pool]
        metrics["diag_acc"] = learner.evaluate(pooled_events)["diag_acc"]
        for lang, pool in probe_pools.items():
            metrics[f"diag_acc_{lang}"] = learner.evaluate(pool)["diag_acc"]

    return metrics


def main():
    global LANGUAGES
    parser = argparse.ArgumentParser()
    parser.add_argument("--events-per-silo-per-disease", type=int, default=12)
    parser.add_argument("--probe-per-silo-per-disease", type=int, default=4)
    parser.add_argument("--n-rounds", type=int, default=8)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--device", default="cpu")
    parser.add_argument(
        "--languages", default="en,es,fr,et",
        help="Comma-separated subset of en,es,fr,et -- one silo per language.",
    )
    parser.add_argument(
        "--backbone", default="distilbert-base-multilingual-cased",
        help="Multilingual backbone (default works for en/es/fr/et; "
             "distilbert-base-uncased would not tokenize es/fr/et meaningfully).",
    )
    args = parser.parse_args()
    LANGUAGES = [l.strip() for l in args.languages.split(",") if l.strip()]

    from fl.aggregation import fedavg
    from fl.learner import FLLearner
    from fl.lora import LoRAConfig
    from simulation.patient_llm import PatientLLMClient

    client = PatientLLMClient()
    if not client.health_check():
        raise SystemExit(
            "Ollama unreachable at localhost:11434 -- this bonus experiment "
            "requires live phi3:mini generation (no phrase-bank fallback for "
            "non-English languages). Run `ollama serve` first."
        )

    print(f"Generating training events for {len(LANGUAGES)} silos "
          f"({args.events_per_silo_per_disease} x {len(DISEASES)} diseases each)...")
    train_pools = {
        lang: _generate_events(lang, args.events_per_silo_per_disease, args.seed, client)
        for lang in LANGUAGES
    }

    print("Generating probe set...")
    probe_pools = {
        lang: _generate_events(lang, args.probe_per_silo_per_disease, args.seed + 999, client)
        for lang in LANGUAGES
    }
    probe_texts = [ev["text"] for pool in probe_pools.values() for ev in pool]
    probe_disease = [ev["gt_disease"] for pool in probe_pools.values() for ev in pool]
    probe_language = [ev["language"] for pool in probe_pools.values() for ev in pool]

    lora_cfg = LoRAConfig(model_name_or_path=args.backbone, num_labels=2)
    learners = [
        FLLearner(lora_config=lora_cfg, label_space="fictional_disease",
                  min_events_to_train=4, device=args.device)
        for _ in LANGUAGES
    ]

    # Round 0 (pre-training) baseline.
    round0 = _evaluate(learners[0], probe_texts, probe_disease, probe_language, probe_pools)
    learners[0].release()
    print(f"\nRound 0 (pre-training): {round0}")

    curve = [{"round": 0, **round0}]
    global_weights = None
    for r in range(args.n_rounds):
        rnd = r + 1
        round_weights, train_sizes = [], []
        for lang, learner in zip(LANGUAGES, learners):
            if global_weights is not None:
                learner.set_weights(global_weights)
            n_trained, _ = learner.train(train_pools[lang], round_num=rnd)
            train_sizes.append(n_trained)
            round_weights.append(learner.get_weights())
            learner.release()

        global_weights = fedavg(round_weights, [max(1, n) for n in train_sizes])
        learners[0].set_weights(global_weights)
        metrics = _evaluate(learners[0], probe_texts, probe_disease, probe_language, probe_pools)
        learners[0].release()
        print(f"Round {rnd}: {metrics}")
        curve.append({"round": rnd, **metrics})

    # Final-round global-model embeddings, for a 2D visualization of the
    # global clusters (disease vs. language) -- not used by any metric above.
    learners[0].set_weights(global_weights)
    final_embs = _extract_cls(learners[0], probe_texts)
    learners[0].release()
    coords = _project_umap(final_embs, seed=args.seed)
    embedding_dump = {
        "coords": coords.tolist(),
        "disease": probe_disease,
        "language": probe_language,
    }
    lang_tag = "-".join(LANGUAGES)
    emb_path = OUT_DIR / f"multilingual_silos_{lang_tag}_seed{args.seed}_final_embeddings.json"
    with emb_path.open("w") as f:
        json.dump(embedding_dump, f, indent=2)
    print(f"Saved: {emb_path}")

    summary = {
        "experiment": "bonus_multilingual_silos",
        "languages": LANGUAGES,
        "diseases": DISEASES,
        "backbone": args.backbone,
        "n_rounds": args.n_rounds,
        "seed": args.seed,
        "curve": curve,
        "final": curve[-1],
    }
    out_path = OUT_DIR / f"multilingual_silos_{lang_tag}_seed{args.seed}.json"
    with out_path.open("w") as f:
        json.dump(summary, f, indent=2)
    print(f"\nSaved: {out_path}")


if __name__ == "__main__":
    main()
