"""
Ollama diagnostic client — multi-turn LLM doctor (§3.4).

Conversation protocol per patient:
  1. Patient sends opening statement (natural language)
  2. Doctor asks ONE symptom follow-up question
  3. Patient answers (PatientLLMClient if available, else SymptomNarrator)
  4. Doctor requests objective vitals: {"type": "vitals_request"}
  5. System injects formatted vitals from CaseTable
  6. Doctor delivers triage decision

The doctor LLM never sees severity s numerically — only natural-language
reports and a vitals panel identical to what a triage nurse would hand over.

Raises OllamaUnavailableError if the doctor model is unreachable.
"""
from __future__ import annotations

import json
import urllib.request
import urllib.error
from simulation.models import DiagnosticAction, DiagnosticEvent

OLLAMA_URL  = "http://localhost:11434/api/chat"
MODEL       = "phi3:mini"
TIMEOUT_SEC = 60
MAX_TURNS   = 6   # safety cap — prevents loops if model keeps asking questions

SYSTEM_PROMPT = """\
You are a triage doctor. Each reply is ONE JSON object — no other text.

Before you diagnose, you must first ask the patient one question, then request their vitals.

To ask a question:
{"type": "question", "text": "your question here"}

To request vitals (after the patient has answered):
{"type": "vitals_request"}

To give your diagnosis (only after seeing vitals):
{"type": "decision", "action": "home_recovery or resolve or hospitalise", "label": "mild or moderate or severe", "diagnosis": "brief text", "notes": "one sentence"}

Actions: home_recovery=mild (rest at home), resolve=moderate (needs treatment), hospitalise=severe (admit now).
Output only one JSON object per turn. Never diagnose before seeing vitals.
"""


class OllamaUnavailableError(RuntimeError):
    pass


class OllamaDiagnosticClient:
    """
    Multi-turn Ollama doctor. Blocks until the full conversation completes.
    Conversation is recorded on DiagnosticEvent.conversation as [{role, text}].

    patient_llm : PatientLLMClient | None
        If provided, patient follow-up answers are generated by the small
        patient model.  Falls back to SymptomNarrator templates otherwise.

    Few-shot learning: call update_examples() after each FL round to inject
    the best past conversations as prior context.
    """

    def __init__(self, model: str = MODEL, url: str = OLLAMA_URL,
                 timeout: int = TIMEOUT_SEC, patient_llm=None):
        self.model        = model
        self.url          = url
        self.timeout      = timeout
        self._patient_llm = patient_llm
        self._examples:   list[dict] = []

    # ── Public interface ──────────────────────────────────────────────────────

    def diagnose(self, event: DiagnosticEvent, _queue=None) -> DiagnosticEvent:
        """
        Run the full patient-doctor pipeline for one DiagnosticEvent.
        event.conversation must already contain the opening patient statement.
        Raises OllamaUnavailableError if the doctor model is unreachable.
        """
        messages     = self._build_initial_messages(event)
        vitals_taken = False
        turn         = 0

        def _status(msg: str) -> None:
            if _queue:
                _queue.update_status(event.agent_id, msg)

        while turn < MAX_TURNS:
            _status(f"Doctor thinking… (turn {turn + 1})")
            raw    = self._call_ollama(messages)
            parsed = self._parse_response(raw)
            turn  += 1

            if parsed["type"] == "question" and not vitals_taken and parsed.get("text"):
                # Step 1 — symptom follow-up
                q_text = parsed["text"]
                event.conversation.append({"role": "doctor",  "text": q_text})
                messages.append({"role": "assistant", "content": json.dumps(parsed)})

                _status("Patient answering…")
                answer = self._patient_answer(event, q_text)
                event.conversation.append({"role": "patient", "text": answer})
                messages.append({"role": "user", "content": answer})

            elif parsed["type"] == "vitals_request" and not vitals_taken:
                # Step 2 — objective vitals panel
                vitals_str = self._format_vitals(event)
                event.conversation.append({"role": "doctor", "text": "[measuring vitals]"})
                event.conversation.append({"role": "vitals",  "text": vitals_str})
                messages.append({"role": "assistant", "content": json.dumps(parsed)})
                messages.append({"role": "user",      "content": vitals_str})
                vitals_taken = True

            else:
                # Step 3 — decision (or force one if model got stuck)
                if parsed["type"] != "decision":
                    parsed = self._force_decision(messages)

                action_map = {
                    "home_recovery": DiagnosticAction.RECOVER,
                    "resolve":       DiagnosticAction.RESOLVE,
                    "hospitalise":   DiagnosticAction.HOSPITALISE,
                    "hospitalize":   DiagnosticAction.HOSPITALISE,
                }
                event.action       = action_map.get(
                    (parsed.get("action") or "").lower(), DiagnosticAction.RECOVER
                )
                event.oracle_label = parsed.get("label") or "unknown"
                event.diagnosis    = (parsed.get("diagnosis") or "")[:100]
                event.notes        = (parsed.get("notes") or "")[:160]
                action_str = (parsed.get("action") or "unknown").replace("_", " ")
                event.conversation.append({
                    "role": "doctor",
                    "text": (
                        f"Diagnosis: {event.diagnosis}. "
                        f"Outcome: {action_str} ({event.oracle_label}). "
                        f"{event.notes}"
                    ),
                })
                break

        return event

    def update_examples(self, events: list, max_per_tier: int = 2) -> None:
        """
        Refresh the few-shot example bank from a batch of processed DiagnosticEvents.

        Selects up to max_per_tier correct conversations per management tier,
        ordered by fewest turns.  Call after each FL round so the doctor
        improves calibration over time.
        """
        mgmt_to_action = {
            "home rest":   DiagnosticAction.RECOVER,
            "treat":       DiagnosticAction.RESOLVE,
            "hospitalise": DiagnosticAction.HOSPITALISE,
        }

        by_tier: dict[str, list[tuple[int, dict]]] = {t: [] for t in mgmt_to_action}

        for ev in events:
            if not ev.ground_truth or not ev.action or not ev.conversation:
                continue
            parts = ev.ground_truth.rsplit(" / ", 1)
            if len(parts) != 2:
                continue
            expected = mgmt_to_action.get(parts[1])
            if expected != ev.action:
                continue

            patient_turns = [t["text"] for t in ev.conversation if t["role"] == "patient"]
            if not patient_turns:
                continue

            doctor_json = json.dumps({
                "type":      "decision",
                "action":    ev.action.value,
                "label":     ev.oracle_label or "unknown",
                "diagnosis": ev.diagnosis or "",
                "notes":     ev.notes or "",
            })

            n_turns = len(ev.conversation)
            by_tier[parts[1]].append((n_turns, {
                "patient":     patient_turns[0],
                "doctor_json": doctor_json,
            }))

        self._examples = []
        for tier_examples in by_tier.values():
            tier_examples.sort(key=lambda x: x[0])
            self._examples.extend(ex for _, ex in tier_examples[:max_per_tier])

    def num_examples(self) -> int:
        return len(self._examples)

    def health_check(self) -> bool:
        try:
            req = urllib.request.Request(
                "http://localhost:11434/api/tags", method="GET"
            )
            with urllib.request.urlopen(req, timeout=5):
                return True
        except Exception:
            return False

    # ── Private helpers ───────────────────────────────────────────────────────

    def _patient_answer(self, event: DiagnosticEvent, question: str) -> str:
        """Generate a patient follow-up answer, preferring the patient LLM."""
        from simulation.symptom_language import Personality, SymptomNarrator
        personality = event.personality or Personality.NEUTRAL

        if self._patient_llm is not None:
            try:
                return self._patient_llm.followup_answer(
                    question, event.severity, personality,
                    case_table=event.case_table, day=event.days_infected,
                )
            except Exception:
                pass

        return SymptomNarrator().followup_answer(
            event.symptoms, personality, question,
            case_table=event.case_table, day=event.days_infected,
        )

    def _format_vitals(self, event: DiagnosticEvent) -> str:
        """Format CaseTable vitals as a triage-nurse-style panel string."""
        ct  = event.case_table
        day = event.days_infected
        if ct is None:
            return "[VITALS] Unavailable — proceed on clinical history alone."

        hr     = ct.get("HR",      day)
        temp   = ct.get("temp",    day)
        spo2   = ct.get("SpO2",    day)
        rr     = ct.get("RR",      day)
        bp_sys = ct.get("BP_sys",  day)
        bp_dia = ct.get("BP_dia",  day)
        pain   = ct.get("pain",    day)
        fat    = ct.get("fatigue", day)

        parts = []
        if hr     is not None: parts.append(f"HR {hr:.0f} bpm")
        if temp   is not None: parts.append(f"Temp {temp:.1f}°C")
        if spo2   is not None: parts.append(f"SpO2 {spo2:.0f}%")
        if rr     is not None: parts.append(f"RR {rr:.0f}/min")
        if bp_sys is not None and bp_dia is not None:
            parts.append(f"BP {bp_sys:.0f}/{bp_dia:.0f} mmHg")
        if pain   is not None: parts.append(f"Pain {pain:.0f}/10")
        if fat    is not None: parts.append(f"Fatigue {fat:.0f}/10")

        return "[VITALS] " + " | ".join(parts)

    def _build_initial_messages(self, event: DiagnosticEvent) -> list[dict]:
        opening = next(
            (t["text"] for t in event.conversation if t["role"] == "patient"),
            "I am not feeling well.",
        )
        messages = [{"role": "system", "content": SYSTEM_PROMPT}]
        for ex in self._examples:
            messages.append({"role": "user",      "content": ex["patient"]})
            messages.append({"role": "assistant", "content": ex["doctor_json"]})
        messages.append({"role": "user", "content": opening})
        return messages

    def _call_ollama(self, messages: list[dict]) -> str:
        payload = json.dumps({
            "model":    self.model,
            "messages": messages,
            "stream":   False,
            "format":   "json",
            "options":  {"temperature": 0.2, "num_predict": 120},
        }).encode()

        req = urllib.request.Request(
            self.url,
            data    = payload,
            headers = {"Content-Type": "application/json"},
            method  = "POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                body = json.loads(resp.read())
                return body.get("message", {}).get("content", "")
        except urllib.error.URLError as exc:
            raise OllamaUnavailableError(
                f"Cannot reach Ollama at {self.url}: {exc.reason}"
            ) from exc
        except Exception as exc:
            raise OllamaUnavailableError(f"Ollama request failed: {exc}") from exc

    def _parse_response(self, raw: str) -> dict:
        try:
            data = json.loads(raw)
        except (json.JSONDecodeError, ValueError):
            return {"type": "decision", "action": "home_recovery",
                    "label": "parse_error",
                    "notes": f"Unparseable output: {raw[:60]}"}

        # Ideal flat response: {"type": "question"|"vitals_request"|"decision", ...}
        known = ("question", "vitals_request", "decision")
        top_type = data.get("type", "")
        if top_type in known and (top_type != "question" or data.get("text")):
            return data

        # phi3:mini sometimes nests responses: {"Follow-up": {"type":"question","text":"..."},...}
        # Walk one level of nesting and pick the first well-formed action.
        for val in data.values():
            if not isinstance(val, dict):
                continue
            vtype = val.get("type", "")
            if vtype == "question" and val.get("text"):
                return val
            if vtype == "vitals_request":
                return val
            if vtype == "decision" and val.get("action"):
                return val

        # Fall back: if top-level has "action" it's a malformed decision
        if "action" in data:
            data["type"] = "decision"
            return data

        # Advance protocol: skip to vitals request rather than failing silently
        return {"type": "vitals_request"}

    def _force_decision(self, messages: list[dict]) -> dict:
        messages = messages + [{
            "role": "user",
            "content": "Please give your final triage decision now.",
        }]
        raw    = self._call_ollama(messages)
        parsed = self._parse_response(raw)
        if parsed.get("type") == "decision":
            return parsed
        return {"type": "decision", "action": "home_recovery",
                "label": "unknown", "notes": "Could not obtain decision from model."}
